### ISSUE TITLE
sass missing variable src/assets/scss/core/elements/_forms.scss is missing check-checked-inverse

### ISSUE THREAD

**Issue by kopax** [cruip/open-react-template#29]
I am encountering the following error after updating some deps:

```bash
Cannot read property 'toLowerCase' of undefined
CompileError: Begins at CSS selector .invert-color .form-checkbox input:checked,.invert-color .form-radio input:checked
```

After digging, it seems that this is due to ` src/assets/scss/core/elements/_forms.scss`:

```scss
	.form-checkbox,
	.form-radio {

		input {

			&:checked {
				background-color: color-bg(check-checked-inverse) !important;
				border-color: color-bg(check-checked-inverse) !important;
			}
		}
	}
```

Removing `!important` works, however, this will never work unless `check-checked-inverse` is set somewhere, adding to `src/assets/scss/settings/base/_colors.scss`:

```diff

// Misc elements: background color
$bg--color: (
	body: 			get-color(dark, 1),
	body-shadow:	0 20px 48px rgba(get-color(dark, 1), .8),	// body shadow when a boxed layout is used (set to null if don't want a shadow)
	body-outer:		lighten(get-color(dark, 1), 2%),			// outer bg color when a boxed layout is used
	bg-color: 		lighten(get-color(light, 1), 9%),			// .has-bg-color helper class
	shadow: 		0 24px 64px rgba(get-color(dark, 1), .64),	// .has-shadow helper class
	code: 			darken(get-color(dark, 1), 3%),
	code-inverse:	darken(get-color(dark, 1), 3%),
+	check-checked-inverse:	darken(get-color(dark, 1), 3%)
);
```

Will fix the error (not sure if this is the right color thought)
